[project]
name = "cuboid"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "np>=1.0.2",
    "numpy>=2.4.4",
    "shapely>=2.1.2",
]

[dependency-groups]
dev = [
    "deduplicate>=0.1.0",
    "vpype>=1.15.0",
    "zensical>=0.0.37",
]
